find_path(EPOXY_INCLUDE_DIRS NAMES epoxy/gl.h PATH_SUFFIXES include)

if(EPOXY_INCLUDE_DIRS)
	get_filename_component(EPOXY_PREFIX "${EPOXY_INCLUDE_DIRS}" DIRECTORY)
	find_library(EPOXY_LIBRARY_RELEASE NAMES epoxy_0 epoxy PATHS "${EPOXY_PREFIX}/lib" NO_DEFAULT_PATH)
	find_library(EPOXY_LIBRARY_DEBUG NAMES epoxy_0d epoxy_d epoxy_0 epoxy PATHS "${EPOXY_PREFIX}/debug/lib" NO_DEFAULT_PATH)
endif()

if(NOT EPOXY_LIBRARY_RELEASE)
	find_library(EPOXY_LIBRARY_RELEASE NAMES epoxy_0 epoxy)
endif()

if(EPOXY_INCLUDE_DIRS AND (EPOXY_LIBRARY_RELEASE OR EPOXY_LIBRARY_DEBUG))
	if(NOT TARGET epoxy::epoxy)
		add_library(epoxy::epoxy UNKNOWN IMPORTED GLOBAL)
		set_target_properties(epoxy::epoxy PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${EPOXY_INCLUDE_DIRS}")

		if(EPOXY_LIBRARY_RELEASE)
			set_property(TARGET epoxy::epoxy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
			set_target_properties(epoxy::epoxy PROPERTIES
				IMPORTED_LOCATION "${EPOXY_LIBRARY_RELEASE}"
				IMPORTED_LOCATION_RELEASE "${EPOXY_LIBRARY_RELEASE}"
				MAP_IMPORTED_CONFIG_MINSIZEREL Release
				MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release)
		endif()
		if(EPOXY_LIBRARY_DEBUG)
			set_property(TARGET epoxy::epoxy APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
			set_target_properties(epoxy::epoxy PROPERTIES IMPORTED_LOCATION_DEBUG "${EPOXY_LIBRARY_DEBUG}")
		endif()

		if(NOT EPOXY_LIBRARY_RELEASE)
			set_target_properties(epoxy::epoxy PROPERTIES
				IMPORTED_LOCATION "${EPOXY_LIBRARY_DEBUG}"
				MAP_IMPORTED_CONFIG_MINSIZEREL Debug
				MAP_IMPORTED_CONFIG_RELEASE Debug
				MAP_IMPORTED_CONFIG_RELWITHDEBINFO Debug)
		elseif(NOT EPOXY_LIBRARY_DEBUG)
			set_target_properties(epoxy::epoxy PROPERTIES MAP_IMPORTED_CONFIG_DEBUG Release)
		endif()
	endif()

	set(EPOXY_LIBRARIES epoxy::epoxy)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(epoxy REQUIRED_VARS EPOXY_INCLUDE_DIRS EPOXY_LIBRARIES)

mark_as_advanced(EPOXY_INCLUDE_DIRS EPOXY_LIBRARY_RELEASE EPOXY_LIBRARY_DEBUG)
